name: hugo publish

#on: workflow_dispatch
on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Asciidoctor      
      run: |
           pip3 install --no-cache-dir actdiag blockdiag nwdiag seqdiag
           gem install asciidoc
           gem install asciidoctor
           gem install asciidoctor-diagram
           gem install asciidoctor-html5s

    - name: Build
      run: |
          ##which asciidoctor
          ##alias asciidoctor="asciidoctor --require asciidoctor-diagram --attribute=experimental=true --attribute=icons=font"
          ##alias
          hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        #ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        #EXTERNAL_REPOSITORY: vincent-gou/vincent-gou.github.io
        #PUBLISH_BRANCH: master
        #PUBLISH_DIR: ./public
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
        external_repository: vincent-gou/vincent-gou.github.io
